name: Node.js Package

on:
  push:
    branches:
      - main

jobs:

  version-bump:
    if: "!startsWith(github.event.head_commit.message, 'chore(release):')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - uses: actions/setup-node@v2
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: git config --global user.email "dannybrown37@gmail.com"
    - run: git config --global user.name "Danny Brown (CI)"
    - run: npm install --save-dev standard-version
    - run: npx standard-version
    - run: git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/dannybrown37/fast-pr.git
    - run: git push --follow-tags origin main
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  publish-npm:
    needs: version-bump
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: actions/setup-node@v2
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
